### ISSUE TITLE
Asynchronous API

### ISSUE THREAD

**Issue by LourensVeen** [MD-Studio/lie_md#11]
Right now the service blocks while the MD is running, we should have an asynchronous API so that it can handle requests in the mean time.

**Comment by LourensVeen** [comment]
After discussing with @felipeZ, here's how we think this is best implemented:
- Add a Future object to the MDStudio type registry, which holds an endpoint name and a set of arguments.
- If a microservice wants to offer an asynchronous API, have it offer one endpoint to submit an operation, and another one that returns the result. These can be called anything and have any inputs and outputs, but the submit operation returns a Future.
- If the workflow engine is asked to call an endpoint that returns a Future (which it can determine from the schema), it will do so, store the future, and periodically call the endpoint described in the Future with the arguments from the Future.
- The `status` property that is returned with results will be extended to include a `running` value.
- The result-returning endpoint will either return an error with `status = failed`, if the operation encountered an error, or `status = running` with no payload if the operation is in progress, or `status = completed` with the result if the operation is done.
- The result will only be available once, a second call to the result-returning endpoint after the result was returned will give an error.
- Perhaps a call to the result-returning endpoint when the operation is in progress could return `status = running` with a log as a payload?

@marcvdijk does that make sense to you?

**Comment by marcvdijk** [comment]
He Lourens and Felipe,

If I understand well, a Future is a JSON message returned by the service indicating that it is processing the request and informing the user to “call back” on a dedicated endpoint for status 
updates and the results.
That makes allot of sense to me. I would say it is up to the receiver of this message how to deal with it also with respect to the code that may wrap this message I believe your refers to this 
as the “Future object”. The JSON Schema is than the official reference for this type of “response”.  I’m not sure what you mean with the “MDStudio type registry”, do we have one? JSON schema’s?

**Comment by LourensVeen** [comment]
I may be messing up the terminology a bit. AFAIK, there's a central store with JSON schemas, which essentially holds type definitions for the various messages being sent between the microservices. I'm proposing to add another JSON schema there named Future. A long-running function will then return such an object, which gives the caller just enough information to check if the result is ready, and when it is, get it.

Indeed it's up to the caller to decide what to do exactly, how often to check, etc. The called endpoint could even return a reference to itself, e.g. it could be designed so that the user just repeats the same call again. To the caller, it all doesn't matter, they just call the endpoint they get with the provided parameters.

So this gives flexibility to the microservice API designer, it allows generic components like the workflow runner to deal with any asynchronous API without custom programming, and it requires only one new JSON schema and a small extension.

**Comment by marcvdijk** [comment]
Indeed, than we are on the same level regarding this API implementation.
I think this would be a good way to go.
