### ISSUE TITLE
Job hangs if connection to HPC resource failed

### ISSUE THREAD

**Issue by marcvdijk** [MD-Studio/lie_md#12]
If lie_md/cerise is unable to connect to the external HPC resource the job hangs.
Should maybe try a few times and then fail the job.

**Comment by LourensVeen** [comment]
Yep. This is not an lie_md issue though, it's up to Cerise to manage the connection to the HPC machine and reconnect as needed and as available. This is Cerise issue https://github.com/MD-Studio/cerise/issues/78, and it's already solved on the develop branch with the port to Cerulean.
